import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { AppShell } from "../components/layout/AppShell";
import { EmptyState } from "../components/ui/EmptyState";
import { StatusBadge } from "../components/ui/StatusBadge";
import { useAuth } from "../hooks/useAuth";
import { useHistoryList } from "../hooks/useAssignments";
export const DashboardPage = () => {
    const { signOut } = useAuth();
    const historyQuery = useHistoryList();
    const items = historyQuery.data?.items ?? [];
    const recentItems = items.slice(0, 3);
    const completedCount = items.filter((item) => item.status === "completed").length;
    const courseCount = new Set(items.map((item) => item.courseName).filter(Boolean)).size;
    return (_jsxs(AppShell, { onSignOut: () => void signOut(), children: [_jsxs("section", { className: "grid gap-6 xl:grid-cols-[1.2fr_0.8fr]", children: [_jsxs("div", { className: "rounded-[40px] border border-ink/8 bg-white p-8 shadow-soft md:p-10", children: [_jsx("p", { className: "text-sm uppercase tracking-[0.25em] text-ink/45", children: "Dashboard" }), _jsx("h1", { className: "mt-4 max-w-3xl font-display text-5xl leading-tight text-ink md:text-6xl", children: "Understand the assignment before you start writing." }), _jsx("p", { className: "mt-4 max-w-2xl text-sm leading-8 text-ink/68", children: "Build a clearer plan for every brief, keep your past explanations organized, and use each result as a practical study guide instead of a passive summary." }), _jsxs("div", { className: "mt-8 flex flex-wrap gap-3", children: [_jsx(Link, { className: "rounded-full bg-accent px-5 py-3 text-sm font-semibold text-white", to: "/new-explanation", children: "Create new explanation" }), _jsx(Link, { className: "rounded-full border border-ink/10 bg-white px-5 py-3 text-sm font-semibold text-ink", to: "/history", children: "View history" })] })] }), _jsx("div", { className: "grid gap-4 sm:grid-cols-3 xl:grid-cols-1", children: [
                            ["Assignments saved", String(items.length)],
                            ["Completed breakdowns", String(completedCount)],
                            ["Courses tracked", String(courseCount)]
                        ].map(([label, value]) => (_jsxs("div", { className: "rounded-[30px] border border-ink/8 bg-white p-6 shadow-soft", children: [_jsx("p", { className: "text-xs font-semibold uppercase tracking-[0.22em] text-ink/45", children: label }), _jsx("p", { className: "mt-4 font-display text-5xl text-ink", children: value })] }, label))) })] }), _jsxs("section", { className: "mt-8 grid gap-6 lg:grid-cols-[1fr_0.8fr]", children: [_jsxs("div", { children: [_jsxs("div", { className: "mb-4 flex items-center justify-between", children: [_jsx("h2", { className: "font-display text-3xl text-ink", children: "Recent explanations" }), _jsx(Link, { className: "text-sm font-semibold text-accent", to: "/history", children: "See all history" })] }), historyQuery.isLoading ? (_jsx(EmptyState, { title: "Loading history", body: "Fetching your saved assignment explanations." })) : recentItems.length === 0 ? (_jsx(EmptyState, { title: "No saved explanations yet", body: "Create your first explanation to start building a reusable study history." })) : (_jsx("div", { className: "grid gap-4", children: recentItems.map((item) => (_jsxs(Link, { className: "rounded-[30px] border border-ink/8 bg-white p-5 shadow-soft transition hover:-translate-y-1", to: `/result/${item.explanationId}`, children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("p", { className: "font-display text-2xl text-ink", children: item.title ?? "Untitled assignment" }), _jsx("p", { className: "mt-1 text-sm text-ink/60", children: item.courseName ?? "General course" })] }), _jsx(StatusBadge, { status: item.status })] }), _jsx("p", { className: "mt-4 line-clamp-2 text-sm leading-7 text-ink/70", children: item.questionText })] }, item.explanationId))) }))] }), _jsxs("aside", { className: "rounded-[34px] border border-ink/8 bg-white p-6 shadow-soft", children: [_jsx("p", { className: "text-sm uppercase tracking-[0.24em] text-ink/45", children: "Make each result more useful" }), _jsxs("ul", { className: "mt-5 space-y-4 text-sm leading-7 text-ink/75", children: [_jsx("li", { children: "Start with the lecturer-intent section before touching your draft." }), _jsx("li", { children: "Use the step-by-step breakdown to plan your reading order." }), _jsx("li", { children: "Turn key topics into search phrases for library or web research." }), _jsx("li", { children: "Compare common mistakes against your outline before submission." })] })] })] })] }));
};
