import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { Button } from "../components/ui/Button";
export const LandingPage = () => (_jsxs("div", { className: "min-h-screen bg-sand px-4 py-4 text-ink md:px-6", children: [_jsx("header", { className: "sticky top-4 z-40 mx-auto max-w-6xl rounded-full border border-ink/10 bg-white/92 px-4 py-3 shadow-soft backdrop-blur", children: _jsxs("div", { className: "flex items-center justify-between gap-4", children: [_jsx("div", { className: "font-display text-xl font-semibold md:text-2xl", children: "Assignment Explainer" }), _jsxs("nav", { className: "hidden items-center gap-2 md:flex", children: [_jsx("a", { className: "rounded-full px-4 py-2 text-sm font-semibold text-ink/65", href: "#how-it-works", children: "How it works" }), _jsx("a", { className: "rounded-full px-4 py-2 text-sm font-semibold text-ink/65", href: "#student-value", children: "Why students use it" })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Link, { to: "/login", className: "hidden text-sm font-semibold text-ink/70 md:inline-flex", children: "Log in" }), _jsx(Link, { to: "/signup", children: _jsx(Button, { className: "bg-accent", children: "Create account" }) })] })] }) }), _jsxs("div", { className: "mx-auto mt-8 max-w-6xl space-y-8 pb-12", children: [_jsxs("section", { className: "grid gap-6 lg:grid-cols-[1.15fr_0.85fr]", children: [_jsxs("div", { className: "rounded-[42px] border border-ink/8 bg-white p-8 shadow-soft md:p-12", children: [_jsx("p", { className: "inline-flex rounded-full bg-mist px-4 py-2 text-xs font-semibold uppercase tracking-[0.25em] text-teal", children: "Built for Cavendish students" }), _jsx("h1", { className: "mt-6 max-w-4xl font-display text-5xl leading-tight md:text-7xl", children: "Turn one assignment brief into a clearer plan, structure, and study path." }), _jsx("p", { className: "mt-6 max-w-3xl text-base leading-8 text-ink/70 md:text-lg", children: "Paste the question once and get a cleaner explanation, what your lecturer is really asking for, research priorities, writing structure, and common traps before you waste time drafting the wrong thing." }), _jsxs("div", { className: "mt-8 flex flex-wrap gap-3", children: [_jsx(Link, { to: "/signup", children: _jsx(Button, { className: "bg-accent", children: "Start free" }) }), _jsx(Link, { to: "/login", children: _jsx(Button, { className: "border border-ink/10 bg-white !text-ink hover:bg-sand", children: "I already have an account" }) })] })] }), _jsxs("aside", { className: "rounded-[42px] border border-ink/8 bg-ink p-8 text-white shadow-soft", children: [_jsx("p", { className: "text-xs font-semibold uppercase tracking-[0.25em] text-white/55", children: "What students get" }), _jsx("div", { className: "mt-6 space-y-4", children: [
                                        ["Simplified explanation", "Understand the actual task before you begin reading or writing."],
                                        ["Study direction", "See the best topics to research and the order to tackle them."],
                                        ["Writing structure", "Break the assignment into sections that match the brief."],
                                        ["Mistake prevention", "Catch weak arguments, missing scope, and common reasoning slips early."]
                                    ].map(([title, body]) => (_jsxs("div", { className: "rounded-[28px] border border-white/10 bg-white/5 p-5", children: [_jsx("h2", { className: "font-display text-2xl", children: title }), _jsx("p", { className: "mt-2 text-sm leading-7 text-white/75", children: body })] }, title))) })] })] }), _jsx("section", { id: "how-it-works", className: "grid gap-4 md:grid-cols-3", children: [
                        ["1. Paste the assignment", "Use the original brief, question, or lecturer instructions."],
                        ["2. Get a guided breakdown", "The app explains the task, structure, key topics, and reasoning path."],
                        ["3. Save and return later", "Keep a history of past assignments for revision and comparison."]
                    ].map(([title, body]) => (_jsxs("div", { className: "rounded-[32px] border border-ink/8 bg-white p-6 shadow-soft", children: [_jsx("h2", { className: "font-display text-3xl text-ink", children: title }), _jsx("p", { className: "mt-3 text-sm leading-7 text-ink/70", children: body })] }, title))) }), _jsx("section", { id: "student-value", className: "rounded-[42px] border border-ink/8 bg-white p-8 shadow-soft md:p-10", children: _jsxs("div", { className: "grid gap-8 lg:grid-cols-[0.9fr_1.1fr]", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-semibold uppercase tracking-[0.25em] text-ink/45", children: "Why it helps" }), _jsx("h2", { className: "mt-4 font-display text-5xl leading-tight text-ink", children: "More than a summary. It helps students think, plan, and write better." })] }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2", children: [
                                    "Clarifies command words and hidden expectations in the brief.",
                                    "Turns long assignment instructions into a manageable order of work.",
                                    "Highlights which topics deserve research before drafting begins.",
                                    "Shows what weak reasoning or common fallacies could cost marks."
                                ].map((item) => (_jsx("div", { className: "rounded-[26px] border border-ink/6 bg-sand p-5 text-sm leading-7 text-ink/75", children: item }, item))) })] }) })] })] }));
